# fmt: off
_classification_actes_dict = dict()
_classification_actes_dict["1"] = "Commande Publique"
_classification_actes_dict["1.1"] = "Commande Publique/Marches publics"
_classification_actes_dict["1.2"] = "Commande Publique/Delegation de service public"
_classification_actes_dict["1.3"] = "Commande Publique/Conventions de Mandat"
_classification_actes_dict["1.4"] = "Commande Publique/Autres types de contrats"
_classification_actes_dict["1.5"] = "Commande Publique/Transactions /protocole d accord transactionnel"
_classification_actes_dict["1.6"] = "Commande Publique/Actes relatifs a la maitrise d oeuvre"
_classification_actes_dict["1.7"] = "Commande Publique/Actes speciaux et divers"

_classification_actes_dict["2"] = "Urbanisme"
_classification_actes_dict["2.1"] = "Urbanisme/Documents d urbanisme"
_classification_actes_dict["2.2"] = "Urbanisme/Actes relatifs au droit d occupation ou d utilisation des sols"
_classification_actes_dict["2.3"] = "Urbanisme/Droit de preemption urbain"

_classification_actes_dict["3"] = "Domaine et patrimoine"
_classification_actes_dict["3.1"] = "Domaine et patrimoine/Acquisitions"
_classification_actes_dict["3.2"] = "Domaine et patrimoine/Alienations"
_classification_actes_dict["3.3"] = "Domaine et patrimoine/Locations"
_classification_actes_dict["3.4"] = "Domaine et patrimoine/Limites territoriales"
_classification_actes_dict["3.5"] = "Domaine et patrimoine/Autres actes de gestion du domaine public"
_classification_actes_dict["3.6"] = "Domaine et patrimoine/Autres actes de gestion du domaine prive"

_classification_actes_dict["4"] = "Fonction publique"
_classification_actes_dict["4.1"] = "Fonction publique/Personnel titulaires et stagiaires de la F.P.T."
_classification_actes_dict["4.2"] = "Fonction publique/Personnel contractuel"
_classification_actes_dict["4.3"] = "Fonction publique/Fonction publique hospitaliere"
_classification_actes_dict["4.4"] = "Fonction publique/Autres categories de personnels"
_classification_actes_dict["4.5"] = "Fonction publique/Regime indemnitaire"

_classification_actes_dict["5"] = "Institutions et vie politique"
_classification_actes_dict["5.1"] = "Institutions et vie politique/Election executif"
_classification_actes_dict["5.2"] = "Institutions et vie politique/Fonctionnement des assemblees"
_classification_actes_dict["5.3"] = "Institutions et vie politique/Designation de representants"
_classification_actes_dict["5.4"] = "Institutions et vie politique/Delegation de fonctions"
_classification_actes_dict["5.5"] = "Institutions et vie politique/Delegation de signature"
_classification_actes_dict["5.6"] = "Institutions et vie politique/Exercice des mandats locaux"
_classification_actes_dict["5.7"] = "Institutions et vie politique/Intercommunalite"
_classification_actes_dict["5.8"] = "Institutions et vie politique/Decision d ester en justice"

_classification_actes_dict["6"] = "Libertes publiques et pourvoirs de police"
_classification_actes_dict["6.1"] = "Libertes publiques et pourvoirs de police/Police municipale"
_classification_actes_dict["6.2"] = "Libertes publiques et pourvoirs de police/Pouvoir du president du conseil general"
_classification_actes_dict["6.3"] = "Libertes publiques et pourvoirs de police/Pouvoir du president du conseil regional"
_classification_actes_dict["6.4"] = "Libertes publiques et pourvoirs de police/Autres actes reglementaires"
_classification_actes_dict["6.5"] = "Libertes publiques et pourvoirs de police/Actes pris au nom de l Etat et soumis au controle hierarchique"

_classification_actes_dict["7"] = "Finances locales"
_classification_actes_dict["7.1"] = "Finances locales/Decisions budgetaires"
_classification_actes_dict["7.2"] = "Finances locales/Fiscalite"
_classification_actes_dict["7.3"] = "Finances locales/Emprunts"
_classification_actes_dict["7.4"] = "Finances locales/Interventions economiques"
_classification_actes_dict["7.5"] = "Finances locales/Subventions"
_classification_actes_dict["7.6"] = "Finances locales/Contributions budgetaires"
_classification_actes_dict["7.7"] = "Finances locales/Avances"
_classification_actes_dict["7.8"] = "Finances locales/Fonds de concours"
_classification_actes_dict["7.9"] = "Finances locales/Prise de participation (SEM, etc...)"
_classification_actes_dict["7.10"] = "Finances locales/Divers"

_classification_actes_dict["8"] = "Domaines de competences par themes"
_classification_actes_dict["8.1"] = "Domaines de competences par themes/Enseignement"
_classification_actes_dict["8.2"] = "Domaines de competences par themes/Aide sociale"
_classification_actes_dict["8.3"] = "Domaines de competences par themes/Voirie"
_classification_actes_dict["8.4"] = "Domaines de competences par themes/Amenagement du territoire"
_classification_actes_dict["8.5"] = "Domaines de competences par themes/Politique de la ville-habitat-logement"
_classification_actes_dict["8.6"] = "Domaines de competences par themes/Emploi-formation professionnelle"
_classification_actes_dict["8.7"] = "Domaines de competences par themes/Transports"
_classification_actes_dict["8.8"] = "Domaines de competences par themes/Environnement"
_classification_actes_dict["8.9"] = "Domaines de competences par themes/Culture"

_classification_actes_dict["9"] = "Autres domaines de competences"
_classification_actes_dict["9.1"] = "Autres domaines de competences/Autres domaines de competences des communes"
_classification_actes_dict["9.2"] = "Autres domaines de competences/Autres domaines de competences des departements"
_classification_actes_dict["9.3"] = "Autres domaines de competences/Autres domaines de competences des regions"
_classification_actes_dict["9.4"] = "Autres domaines de competences/Voeux et motions"
# fmt: on