"""Ajout pastell_id_d dans publication

Revision ID: af5d41c92194
Revises: be84c3a0dd7f
Create Date: 2022-12-20 10:51:56.313741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5d41c92194'
down_revision = 'be84c3a0dd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('pastell_id_d', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'pastell_id_d')
    # ### end Alembic commands ###
