"""initialisation_migrate

Revision ID: b41a4fe5bd2e
Revises: 
Create Date: 2022-11-30 15:36:48.108818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41a4fe5bd2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entite_pastell_ag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('id_e', sa.Integer(), nullable=False),
    sa.Column('denomination', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametrage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('nic', sa.String(length=5), nullable=False),
    sa.Column('denomination', sa.String(length=256), nullable=False),
    sa.Column('open_data_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('publication_data_gouv_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('publication_udata_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('uid_data_gouv', sa.String(length=256), nullable=True),
    sa.Column('api_key_data_gouv', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siren')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_de_lacte', sa.String(length=20), nullable=False),
    sa.Column('objet', sa.String(length=256), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('publication_open_data', sa.String(length=1), server_default='2', nullable=False),
    sa.Column('date_de_lacte', sa.DateTime(), nullable=False),
    sa.Column('classification_code', sa.String(length=10), nullable=False),
    sa.Column('classification_nom', sa.String(length=100), nullable=False),
    sa.Column('acte_nature', sa.String(length=50), nullable=False),
    sa.Column('envoi_depot', sa.String(length=50), nullable=False),
    sa.Column('date_budget', sa.String(length=10), nullable=True),
    sa.Column('est_masque', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('est_supprime', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('etat', sa.String(length=1), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('nature_autre_detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('hash', sa.String(length=65), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pj_acte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('hash', sa.String(length=65), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pj_acte')
    op.drop_table('acte')
    op.drop_table('publication')
    op.drop_table('parametrage')
    op.drop_table('entite_pastell_ag')
    # ### end Alembic commands ###
